name: dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - sqlalchemy
  - fastapi
  - uvicorn
  - boto3
  - libcxx                
  - libta-lib>=0.6.4
  - python-dotenv
  - pandas>=2.3.2
  - numba>=0.61.2
  - numpy>=2.2.6
  - pandas-ta>=0.4.71b
  - ta-lib>=0.6.4
  - tqdm>=4.67.1
  - pip
  - pip:
      - hummingbot
      - hummingbot-api-client
      - docker
      - nest_asyncio
      - pydantic
      - streamlit>=1.36.0
      - watchdog
      - python-dotenv
      - plotly==5.24.1
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pyyaml
      - pathlib
      - streamlit-authenticator==0.3.2
      - flake8
      - isort
      - pre-commit
      - msgpack>=1.0.5
      - flake8
      - isort
      - pre-commit
      - logfire
      - logfire[fastapi]
      - logfire[system-metrics]
      - aiomqtt>=2.0.0
      - sqlalchemy>=2.0.0
      - asyncpg
      - psycopg2-binary
      - greenlet
      - pydantic-settings

